import type { Metadata } from "next";
import {  Poppins } from 'next/font/google'
import "./globals.css";
import Header from "@/component/header/header";
import Footer from "@/component/footer/footer";

const poppins =  Poppins({weight:'200', subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Southshore",
  description: "Generated by create Ali Abbas",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body className={poppins.className}>
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  );
}
